### ISSUE TITLE
Compilation de l'environnement de prod en erreur

### ISSUE THREAD

**Issue by chauchse** [LINCnil/pia#127]
Bonjour,

Etant novice en node.js, j'ai besoin d'aide pour interpréter l'erreur suivant

`sudo ng serve -e prod --host X.X.X.X --port 80 -d

@angular/compiler-cli@4.4.6 requires typescript@'>=2.1.0 <2.4.0' but 2.4.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/home/schau/pia/node_modules/typescript/lib/typescript.js:16640:109)
    at parseSourceFileWorker (/home/schau/pia/node_modules/typescript/lib/typescript.js:16572:26)
    at Object.parseSourceFile (/home/schau/pia/node_modules/typescript/lib/typescript.js:16521:26)
    at Object.createSourceFile (/home/schau/pia/node_modules/typescript/lib/typescript.js:16371:29)
    at VirtualFileStats.getSourceFile (/home/schau/pia/node_modules/@ngtools/webpack/src/compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile (/home/schau/pia/node_modules/@ngtools/webpack/src/compiler_host.js:206:38)
    at findSourceFile (/home/schau/pia/node_modules/typescript/lib/typescript.js:70246:29)
    at processImportedModules (/home/schau/pia/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/schau/pia/node_modules/typescript/lib/typescript.js:70274:17)
    at processImportedModules (/home/schau/pia/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/schau/pia/node_modules/typescript/lib/typescript.js:70274:17)
    at processImportedModules (/home/schau/pia/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/schau/pia/node_modules/typescript/lib/typescript.js:70274:17)
    at args (/home/schau/pia/node_modules/typescript/lib/typescript.js:70200:85)
    at getSourceFileFromReferenceWorker (/home/schau/pia/node_modules/typescript/lib/typescript.js:70173:34)
    at processSourceFile (/home/schau/pia/node_modules/typescript/lib/typescript.js:70200:13)
`
pour info j'arrive bien à compiler l'environnement de DEV et accéder à l'interface web.

Merci pour votre aide

**Comment by ylachgar** [comment]
@brunto @chauchse 
Bonjour Messieurs,

J'ai deja eu cette erreur et en effet la version de typescript ne fonctionne pas apres downgrade à la version 2.1 donc je laisse la derniere version.
La solution que j'ai trouvé est de n'installer que l'environment prod sur le server de prod et les versions test dev sur la test dev.
Vous pouvez jeter un oeil a notre runbook :)
Je pense que la compilation de la version build prod ne fonctionne pas bien avec la conf.yml.

**Comment by ylachgar** [comment]
@chauchse 

Par expérience, je n'irais pas vers la solution de désinstaller mais bien plus vers une installation clean sans les conf dev et test. Pour répondre précisément à  la question il faudrait supprimer les env Dev et la DB du postgre ainsi qu'update la db conf.yml

**Comment by ylachgar** [comment]
@chauchse @brunto 

J'ai trouvé ou se trouve l'erreur, qu'il faudrait corriger meme si avec l'update du runbook je vais la couvrir 

Il suffit de faire : 

cd pia
cp src/environments/environment.prod.ts.example src/environments/environment.prod.ts

et changer dans le environment.prod.ts la variable **version: '',** par **version: '1.6.0',**

**Comment by chauchse** [comment]
Joli, 👍 

Je confirme, cela a réglé le pb.

J'aurais besoin de 2 précisions 

1 - Comment lancer automatiquement le front en automatique au redémarrage du seveur (le front et le back sont sur le même serveur)

2 - Est-il possible de lier à LDAP l'outil pour récupérer les informations utilisateurs ?

Merci

**Comment by ylachgar** [comment]
My Pleasure :) 

1 - Je pense que c'est assez simple de le lancer en Deamon (voici un lien qui explique bien le truc [ICI](https://openclassrooms.com/courses/faire-un-demon-sous-linux)

2 - En effet, c'est un enhancement que j'ai déjà demander à notre bon @brunto 

Du coup on peux clôturer le Bug (qui n'en ai pas vraiment un) , j'ai ajouté les étapes au Runbook

**Comment by brunto** [comment]
Super effectivement la solution était logique. Merci d'avoir complété le Runbook.
