### ISSUE TITLE
Struggle with npm

### ISSUE THREAD

**Issue by labanane34** [LINCnil/pia#177]
Hi there !

I'm new and trying to install PIA Front and back for work ! So i follow the runbook in the first hand.

But near the end I struggle a lot with npm install, the only command given in the runbook is:
```
cd pia

sudo npm install npm@latest -g
sudo npm install -g @angular/cli
```

Which i did but i have some error with the angular/cli (but not the fisrt one) see below: 

```
@weblinux-pia:~/pia$ sudo npm install -g @angular/cli
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng

> node-sass@4.8.3 install /usr/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-59 : { Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:909:18)
    at sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor' }

> node-sass@4.8.3 postinstall /usr/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.9.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.9.0
gyp verb command install [ '9.9.0' ]
gyp verb install input version string "9.9.0"
gyp verb install installing version: 9.9.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.9.0
gyp verb build dir attempting to create "build" dir: /usr/lib/node_modules/@angular/cli/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/build'
gyp ERR! System Linux 4.4.0-87-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/@angular/cli/node_modules/node-sass
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.8.3 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.8.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @angular/cli@1.7.3
updated 1 package in 21.643s
```

The thing i don't understand is:
- the first command works fine. Why not the second one ?

- I have acces denied with a sudo command, wtf ? So i dig a little. And the directory "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor" does not exist ! In fact i can go to "/usr/lib/node_modules/@angular/cli/node_modules/" the rest node-sass/vendor is missing. But why ?

Can someone point me in the right direction ? I'm not very familiar with the npm/angular environnement, maybe the answer is basic.

Best regards,

LaBanane.

**Comment by labanane34** [comment]
Ok i dig on the web and found some thing, i seen this and did it:

```
the Angular CLI npm install script is not very good... The problem is, that the installer script wants to put the symbolic link ng to /usr/bin/ so you need sudo... But with sudo you cannot install it because...the installer script is not very good ;) But don't worry, you can install it this way:

1.) Fix the permissions by changing the ownership and group of /usr/lib/node_modules/ to your user account: sudo chown -r XXX /usr/lib/node_modules/ and sudo chgrp -r XXX /usr/lib/node_modules/
2.) sudo npm i -g @angular/cli
3.) sudo rm -fr /usr/lib/node_modules/@angular/cli/
4.) sudo chown -r XXX /usr/lib/node_modules/@angular/
5.) sudo chgrp -r XXX /usr/lib/node_modules/@angular/
6.) npm i -g @angular/cli
```

Then i struggle with the installation of node-sass because he is not happy with permision either. So i did a 

`sudo npm install --unsafe-perm -g node-sass`

I don't know how it will impact security late but i just want this PIA to work for now -_-''
And finaly i managed to install all module with no more error ! And have to finish with a:

`sudo npm install --unsafe-perm`

But when i start to "ng build" with the command in the run book i got this:

```
@weblinux-pia:~/pia$ sudo ng build --prod --build-optimizer –sourcemaps –aot=fasle
Your global Angular CLI version (1.7.3) is greater than your local
version (1.7.2). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

@angular/compiler-cli@4.4.6 requires typescript@'>=2.1.0 <2.4.0' but 2.4.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

Date: 2018-03-29T13:38:01.236Z
Hash: 9cf8ee10938f33c6086a
Time: 53933ms
chunk {scripts} scripts.a82a608652dc809d7762.bundle.js (scripts) 498 kB [initial] [rendered]
chunk {0} main.8812f33c2c55ab4b132e.bundle.js (main) 1.74 MB [initial] [rendered]
chunk {1} polyfills.01cdfa654e8c04997c51.bundle.js (polyfills) 64.1 kB [initial] [rendered]
chunk {2} styles.7634cf631f41b414256b.bundle.css (styles) 105 kB [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in /home/irfasud/pia/src/$$_gendir/app/authentication/authentication.component.ngfactory.ts (280,44): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (14,40): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (31,40): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (36,40): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (41,40): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (46,40): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (51,40): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (56,40): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (20,40): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (19,19): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (19,15): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (30,15): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (35,15): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (40,15): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (45,15): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/authentication/authentication.component.html (50,15): Property '_languagesService' is private and only accessible within class 'AuthenticationComponent'.
ERROR in ng:///home/irfasud/pia/src/app/entry/entry-content/risks-cartography/risks-cartography.component.html (29,58): Property '_piaService' is private and only accessible within class 'RisksCartographyComponent'.
```

I dig on the web again try this "sudo ng build --prod --build-optimizer –sourcemaps –aot=fasle" with the flag "-aot=false" but no luck :'(

LaBanane

**Comment by labanane34** [comment]
Ok if i run a more simple command like:

`ng build prod`

Things all good, but when i look to my listen port on my linux:

```
@weblinux-pia:~$ netstat -ltanu
Connexions Internet actives (serveurs et établies)
Proto Recv-Q Send-Q Adresse locale          Adresse distante        Etat
tcp        0      0 127.0.0.1:4200          0.0.0.0:*               LISTEN
tcp        0      0 X.X.X.X:8080      0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN
tcp        0    256 192.168.0.177:22        192.168.60.241:55713    ESTABLISHED
tcp        0      0 X.X.X.X:22        192.168.60.241:59137    ESTABLISHED
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:5432                :::*                    LISTEN
tcp6      32      0 ::1:36264               ::1:5432                CLOSE_WAIT
tcp6      32      0 ::1:36266               ::1:5432                CLOSE_WAIT
udp        0      0 0.0.0.0:68              0.0.0.0:*
udp6       0      0 ::1:52372               ::1:52372               ESTABLISHED
```
I can see my ssh connection, my front on 192.168.0.177:8080 but my ng build listen on 127.0.0.1:4200 even if I enter this command:

`sudo ng serve –e prod –host X.X.X.X –port XXXX`

No matter what, it listen on port 4200 on IP 127.0.0.1 ....

**Comment by labanane34** [comment]
OH MY GAD IT WORK !

So i have to launch the stuff like this:

`ng serve --port 8081 --host 0.0.0.0 --disable-host-check`

So my linux server finaly allow other computer to connect by network.
Hope my struggle help some people ....

**Comment by labanane34** [comment]
Sooooooooooooooo,

I did my own run book base on the one already available. thanks ylachgar for your work !
You can find it here https://mega.nz/#!3MBTwYRS!gvJENGyrHLgejJxpfT5ZloL4Qt66dqVkZqYwznAo6yc
I make it run on stable 16.0.4 LTS ubuntu without user interface, I realy hope my struggle will help some people.
If someone thinks I did something wrong, please tell me !!!! I am not familiar with this environment, I might not respect best practice.

Best regards,

Julien.

**Comment by labanane34** [comment]
Hé ben c'est pas très actif ce projet .....

**Comment by labanane34** [comment]
Bon voila j'ai enfin réussi à faire une version PROD !

Merci à FanchTheSystem pour m'avoir aiguillé et avoir donnée plein d'info sur différent post.
J'ai mis à jours mon petit runbook ..... si ça intéresse certaines personnes, on ne sait jamais.
https://mega.nz/#!CRATWYCI!TFDMmxWeOefEcihwKF7XN4s2yfpaVpGa5K_9X5YguOE

Bonne chance à ceux qui se lance la dedans !

Julien.

**Comment by kevin-atnos** [comment]
Hello,

There is an installation guide available on the "pia-back", you can check it there:
https://github.com/LINCnil/pia-back/wiki

Thank you,
