### ISSUE TITLE
PIA software installer

### ISSUE THREAD

**Issue by ppmotskula** [LINCnil/pia#251]
I've made a script that helps install, configure and control PIA web versions. This has been successfully tested on a 1VCPU/2GB DigitalOcean droplet with Ubuntu 18.04. It also allows you to easily reconfigure your PIA software to be served over https instead of http.

https://gist.github.com/ppmotskula/4288167460de27d22225e4959c44c6c4

**Comment by ppmotskula** [comment]
I just modified the script to make pia and pia-back both run as www-data instead of the calling user.

**Comment by BoehnMa** [comment]
Dear Peeter,
thanks for the great script! Before I tried the script, I spent more than 3 days installing the software. With your script this is done in a few minutes.
However, there was a problem with the installation of the frontend on my system. I am using "Ubuntu 18.04.1 LTS (Bionic Beaver)", ubuntu-18.04.1-live-server-amd64.iso. The problem was that nodejs could not be installed. I could solve the problem by running nodesource_setup.sh. In the end I installed the PIA software with the following commands:

wget -O ~/piactl https://gist.githubusercontent.com/ppmotskula/4288167460de27d22225e4959c44c6c4/raw/034c2607c168066dba846b34c89c2447d0f1a5c7/piactl
cd ~
curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
bash ~/piactl install all 127.0.0.1

**Comment by ppmotskula** [comment]
@BoehnMa nodejs was in 'universe' repository that wasn't enabled by default on live-server. The updated script (v 0.4) now also works on both live-server and desktop editions of Ubuntu 18.04.

**Comment by BoehnMa** [comment]
@ppmotskula perfect! I can now install the software without errors using the following 2 commands:
wget -O ~/piactl https://gist.githubusercontent.com/ppmotskula/4288167460de27d22225e4959c44c6c4/raw/6919f751c6aeee3e0168c33cdae1209785da254d/piactl
bash ~/piactl install all 127.0.0.1

**Comment by ppmotskula** [comment]
@BoehnMa I would make two slight changes:
1. `wget -O ~/piactl https://gist.githubusercontent.com/ppmotskula/4288167460de27d22225e4959c44c6c4/raw`  
\# this gives you the latest piactl including any improvements I might make in the future
2. `bash ~/piactl install all 0.0.0.0`  
\# this makes the software also accessible from other hosts in your network

**Comment by BoehnMa** [comment]
@ppmotskula Sounds good. I will try it.

**Comment by BoehnMa** [comment]
@ppmotskula I reinstalled the PIA software with your improvements and it all worked. 
 
I noticed another small error with the "remove-front" function.  You write "suco" instead of "sudo".

Your script really is a quantum leap in comparison to the previous methods of installation.  It would be wonderful if it could be made more popular so that users can find it right on the PIA project homepage.

**Comment by ppmotskula** [comment]
@BoehnMa thanks, typo fixed.

**Comment by LaboCNIL** [comment]
Hi @ppmotskula 
Thank you for your contribution ! We'll check it to see if we can include it in the tool.

Bests,
LaboCNIL

**Comment by BoehnMa** [comment]
@ppmotskula
I noticed a problem. It was not possible to assign attachments to the "PIA's". I was able to solve the problem by authorizing the group "www-data" on the directory "pia-back" (sudo chown boehnma:www-data ~/pia-back/). After that the directories "upload" and "temp" necessary for attachments could be created below the directory "pia-back". If you have time, it would be great if you could include this in the installation script.
Best regards
BoehnMa

**Comment by gcdonaldson** [comment]
Hi @ppmotskula 
thank you for your efforts.  This was indeed a time saver.  Things seem to be working but I'm a little perplexed by this error.  After installing on an Ubuntu server 18.04.1.0 virtual machine, running _piactl start back_ returns:

_pia@pia:~$ Traceback (most recent call last):
        4: from bin/rails:3:in `<main>'
        3: from bin/rails:3:in `load'
        2: from /home/pia/pia-back/bin/spring:8:in `<top (required)>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)_

The front end starts fine and browsing to the application URL shows things seem to working, but the back end isn't running according to piactl:

_PIA status: backend stopped, frontend running (3197 3198)_

I did try installing spring thinking that might resolve the issue, but the error persists.  Any insight would be appreciated!

**Comment by ppmotskula** [comment]
@BoehnMa Thanks for reporting. Fixed in v.0.7 of the script (`piactl install back` now creates `uploads` and `data` directories and makes them writable to www-data).

**Comment by ppmotskula** [comment]
@gcdonaldson Thanks for reporting. Fixed in v.0.7 of the script (`piactl install back` now calls `gem install bundler`).

**Comment by gcdonaldson** [comment]
@ppmotskula Thanks for the quick reply.  Much appreciated.  Re-installed pia-back and it seems that bundler 2.0.1 is broken in ruby 2.5.1p57.  

`Cloning into 'pia-back'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 588 (delta 6), reused 5 (delta 1), pack-reused 571
Receiving objects: 100% (588/588), 429.41 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (327/327), done.
Traceback (most recent call last):
        2: from /usr/local/bin/bundle:23:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Traceback (most recent call last):
        4: from bin/rake:3:in `<main>'
        3: from bin/rake:3:in `load'
        2: from /home/pia/pia-back/bin/spring:8:in `<top (required)>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
Traceback (most recent call last):
        4: from bin/rake:3:in `<main>'
        3: from bin/rake:3:in `load'
        2: from /home/pia/pia-back/bin/spring:8:in `<top (required)>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
Traceback (most recent call last):
        4: from bin/rake:3:in `<main>'
        3: from bin/rake:3:in `load'
        2: from /home/pia/pia-back/bin/spring:8:in `<top (required)>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
Done. pia-back should now be installed. Start it with 'piactl start back', then go to http://0.0.0.0:3000`

As you'd expect pia-back won't start.  

I removed bundler 2.0.1 and modified your script to install bundler version 1.16.1 with `sudo gem install bundler -v 1.16.1` and pia-back installs and runs.  I do get a warning about bundler 1.16.1 being older than the version of bundler that created the lockfile (1.16.2), but everything works, so that version of bundler might be a better choice.

Many thanks for putting this script together.  It really makes the installation process a breeze!
Regards,
g

**Comment by liberodark** [comment]
Other pia installer for yunohost : https://github.com/YunoHost-Apps/pia_ynh

**Comment by ppmotskula** [comment]
Updated the script to v 0.9.
Now includes a workaround for Puma's failure to perform SSL handshakes with up-to-date Chrome browsers.
Tested with current pia and pia-back on a clean Ubuntu 18.04.2 LTS.

**Comment by brunto** [comment]
@ppmotskula Could you help @tresrob with this issue: https://github.com/LINCnil/pia/issues/399 seems to be related to your script?
Thank you

**Comment by ppmotskula** [comment]
I just updated my script to v 0.10 so that it would still work with current pia and pia-back.

**Comment by laurent95100** [comment]
Hello, 
thank you for your script, I just tested, the access works when I put the ip in the url, on the other hand if I put his name in I have the following error message: 

"Invalid Host header"

Do you know how it could work with his DNS name and not his ip?

Thank you for your help.

**Comment by ppmotskula** [comment]
The development web server included in PIA *might* check the address of the
http request; if you configured the server (by running the script) with an
IP address and access the server via DNS name, you get an error.

**Comment by aelri-c** [comment]
Hi I keep running into a Bundler issue at install of the back end.

Traceback (most recent call last):
        15: from bin/rake:2:in `<main>'
        14: from bin/rake:2:in `require_relative'
        13: from /home/rb5864/pia-back/config/boot.rb:3:in `<top (required)>'
        12: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        11: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        10: from /usr/local/lib/site_ruby/2.5.0/bundler/setup.rb:10:in `<top (required)>'
         9: from /usr/local/lib/site_ruby/2.5.0/bundler/ui/shell.rb:88:in `silence'
         8: from /usr/local/lib/site_ruby/2.5.0/bundler/ui/shell.rb:136:in `with_level'
         7: from /usr/local/lib/site_ruby/2.5.0/bundler/setup.rb:10:in `block in <top (required)>'
         6: from /usr/local/lib/site_ruby/2.5.0/bundler.rb:149:in `setup'
         5: from /usr/local/lib/site_ruby/2.5.0/bundler/runtime.rb:22:in `setup'
         4: from /usr/local/lib/site_ruby/2.5.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
         3: from /usr/local/lib/site_ruby/2.5.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
         2: from /usr/local/lib/site_ruby/2.5.0/bundler/rubygems_integration.rb:223:in `bin_path'
         1: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:252:in `bin_path'
/usr/local/lib/site_ruby/2.5.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /home/XXXX/pia-back/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`

I tried editing the piactl as follows:

---------------
 # remove Gemfile.lock and install latest bundler
  rm Gemfile.lock
  sudo gem install bundler
  sudo bundle update

Also tried 

 # remove Gemfile.lock and install latest bundler
  rm Gemfile.lock
  sudo gem install bundler -v 2.1.4
  
----- 
But get the same issue
