### ISSUE TITLE
[BUG/NEED HELP] Back and Front connection

### ISSUE THREAD

**Issue by snelhard** [LINCnil/pia#433]
Bonjour,

Voici mon problème : 
 Pia-Back installé correctement. (port 3000)
 Pia-Front installé également correctement. (port 80)

Lorsque je souhaite les lier dans le Pia-front (outils -> paramètres) :
Erreur connexion impossible.

Sur le Pia-front j'ai cette erreur : 

> PG::ConnectionBad (fe_sendauth: no password supplied
> ):
> 
> pg (1.1.4) lib/pg.rb:56:in `initialize'
> pg (1.1.4) lib/pg.rb:56:in `new'
> pg (1.1.4) lib/pg.rb:56:in `connect'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `connect'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
> activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
> activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
> activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
> activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
> activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
> activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
> activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
> activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
> railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
> railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
> activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
> activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
> activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
> railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
> rack (2.0.7) lib/rack/runtime.rb:22:in `call'
> activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
> actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
> rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
> rack-cors (1.1.0) lib/rack/cors.rb:100:in `call'
> railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
> /home/rootdom/.rvm/gems/ruby-head/bundler/gems/puma-fc97fdaab229/lib/puma/configuration.rb:227:in `call'
> /home/rootdom/.rvm/gems/ruby-head/bundler/gems/puma-fc97fdaab229/lib/puma/server.rb:660:in `handle_request'
> /home/rootdom/.rvm/gems/ruby-head/bundler/gems/puma-fc97fdaab229/lib/puma/server.rb:474:in `process_client'
> /home/rootdom/.rvm/gems/ruby-head/bundler/gems/puma-fc97fdaab229/lib/puma/server.rb:334:in `block in run'
> /home/rootdom/.rvm/gems/ruby-head/bundler/gems/puma-fc97fdaab229/lib/puma/thread_pool.rb:135:in `block in spawn_thread'

Le fonctionnement du PIA-BACK et PIA-FRONT continue.

 - OS: Ubunto 18
 - Browser : Opera
 - Ruby : 2.5.1p57
 - Rails : 6.0.1
 - node : v13.3.0
 - npm : 6.13.1

Merci !

**Comment by snelhard** [comment]
Update :
La base utilisée est pia_developpement, or j'ai tout fait pour mettre en prod et non en dev. 
après avoir mis les identifiants dans database.yml, j'ai cette erreur (c'est normal) 

> ActiveRecord::NoDatabaseError (FATAL:  database "pia_development" does not exist
> ):

Que faire pour que ça utilise la base de données de prod et non pas de dev ?

**Comment by snelhard** [comment]
Solution trouvée : ajouter un " -e production" lorsqu'on lance le pia-back.
bin/rails s -e production -b HOST -p port
