### ISSUE TITLE
ng build et ng serve en mode prod ne fonctionnent pas

### ISSUE THREAD

**Issue by Logicsystem360** [LINCnil/pia#46]
Bonjour,

Lorsque je veux lancer le PIA front end en mode production, j'obtiens une bonne centaine de lignes de ce type 

ERROR in ng:///home/(user)/pia/src/app/entry/entry-content/validate-pia/validate-pia.component.html (29,14): Property '_piaService' is private and only accessible within class 'ValidatePIAComponent'.

avec "... is private and only accessible within class ..." à chaque ligne

Après quelques recherches, je pense que ca vient des contraintes du AOT d'Angular 
https://github.com/qdouble/angular-webpack2-starter#aot--donts

En revanche, aucun problème en mode "test"

**Comment by fitou13** [comment]
Meme probleme pour compiler la version de prod mais avec une autre erreur : 

pia@ubuntu:~/pia$ ng build -prod
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/home/pia/pia/node_modules/typescript/lib/typescript.js:16640:110)
    at parseSourceFileWorker (/home/pia/pia/node_modules/typescript/lib/typescript.js:16572:26)
    at Object.parseSourceFile (/home/pia/pia/node_modules/typescript/lib/typescript.js:16521:26)
    at Object.createSourceFile (/home/pia/pia/node_modules/typescript/lib/typescript.js:16371:29)
    at VirtualFileStats.getSourceFile (/home/pia/pia/node_modules/@ngtools/webpack/src/compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile 
(/home/pia/pia/node_modules/@ngtools/webpack/src/compiler_host.js:206:38)
    at findSourceFile (/home/pia/pia/node_modules/typescript/lib/typescript.js:70246:29)
    at processImportedModules (/home/pia/pia/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/pia/pia/node_modules/typescript/lib/typescript.js:70274:17)
    at processImportedModules (/home/pia/pia/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/pia/pia/node_modules/typescript/lib/typescript.js:70274:17)
    at processImportedModules (/home/pia/pia/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/pia/pia/node_modules/typescript/lib/typescript.js:70274:17)
    at args (/home/pia/pia/node_modules/typescript/lib/typescript.js:70200:85)
    at getSourceFileFromReferenceWorker (/home/pia/pia/node_modules/typescript/lib/typescript.js:70173:34)
    at processSourceFile (/home/pia/pia/node_modules/typescript/lib/typescript.js:70200:13)


Application fonctionnelle en mode "DEV"

**Comment by Logicsystem360** [comment]
J'ai eu cette erreur, ca vient du src/environment/environment.prod.ts.example qu'il faut renommer sans le example

**Comment by fitou13** [comment]
Merci ! Maintenant je suis effectivement sur le meme probleme que toi @Logicsystem360

**Comment by brunto** [comment]
Bonjour,
Je n'arrive pas à reproduire cette erreur, pouvez-vous m'envoyer un zip de votre dossier PIA que je puisse compiler et voir ce que ça donne ?

**Comment by ylachgar** [comment]
Bonsoir,

J'ai le meme type d'erreur :(avec le zorkaround de renomage de l'example)
 
ng serve build -prod
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 13% building modules 27/28 modules 1 active ...ome/administrator/pia/src/styles.scssNode#moveTo was deprecated. Use Container#append.
Date: 2018-02-01T17:10:14.239Z                                                          
Hash: a29b2f11d74291b5564b
Time: 65304ms
chunk {scripts} scripts.5ca22cd719aff38760de.bundle.js (scripts) 497 kB [initial] [rendered]
chunk {0} polyfills.19e05f30cc2f8291d348.bundle.js (polyfills) 64.3 kB [initial] [rendered]
chunk {1} main.53c15c6bff3c3be967dd.bundle.js (main) 766 kB [initial] [rendered]
chunk {2} styles.7ddadff123c1e5255248.bundle.css (styles) 116 kB [initial] [rendered]
chunk {3} vendor.3e4d7c97537bdeebb3ed.bundle.js (vendor) 1.08 MB [initial] [rendered]
chunk {4} inline.5341ac333e0f2197d62c.bundle.js (inline) 1.45 kB [entry] [rendered]


ERROR in ng:///home/administrator/pia/src/app/entry/entry-content/validate-pia/validate-pia.component.html (39,14): Property '_piaService' is protected and only accessible within class 'ValidatePIAComponent' and its subclasses.
ERROR in ng:///home/administrator/pia/src/app/header/header.component.html (34,22): Property '_translateService' is protected and only accessible within class 'HeaderComponent' and its subclasses.
ERROR in ng:///home/administrator/pia/src/app/header/header.component.html (47,22): Property '_translateService' is protected and only accessible within class 'HeaderComponent' and its subclasses.
ERROR in ng:///home/administrator/pia/src/app/header/header.component.html (53,22): Property '_translateService' is protected and only accessible within class 'HeaderComponent' and its subclasses.
...
ERROR in ng:///home/administrator/pia/src/app/summary/summary.component.html (229,9): Property '_actionPlanService' is protected and only accessible within class 'SummaryComponent' and its subclasses.

webpack: Failed to compile.


Sans le renomage .

ng serve build -prod
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:15457:110)
    at parseSourceFileWorker (/home/administrator/pia/node_modules/typescript/lib/typescript.js:15389:26)
    at Object.parseSourceFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:15338:26)
    at Object.createSourceFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:15192:29)
    at VirtualFileStats.getSourceFile (/home/administrator/pia/node_modules/@ngtools/webpack/src/compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile (/home/administrator/pia/node_modules/@ngtools/webpack/src/compiler_host.js:206:38)
    at findSourceFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:67909:29)
    at processImportedModules (/home/administrator/pia/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:67937:17)
    at processImportedModules (/home/administrator/pia/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:67937:17)
    at processImportedModules (/home/administrator/pia/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:67937:17)
    at processSourceFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:67840:27)
    at processRootFile (/home/administrator/pia/node_modules/typescript/lib/typescript.js:67728:13)
    at /home/administrator/pia/node_modules/typescript/lib/typescript.js:67018:60

**Comment by ylachgar** [comment]
Voila le dossier compressé, il faut plus de 10mb donc je l'ai mis sur mon Gdrive.

https://drive.google.com/file/d/1jR0dPB2yOGK5cmXeFf7F_ruetO0j8DOw/view?usp=sharing

**Comment by ylachgar** [comment]
Pour Info j'ai essayer de downgrade le Angular en version 1.6.1 mais ça ne résout pas le pb de compilation de la version de prod ... ou alors j'ai manqué qqch :)

**Comment by ylachgar** [comment]
Salut les gars,

Désolé de pousser un peu mais des demandes insistante pour la mise en place de la Prod xD.
Si vous pouviez jeter un coup d'oeil ce serait hyper sympa ^^

**Comment by brunto** [comment]
Bonjour,
Je vous encourage à tester la nouvelle version mise en ligne récemment elle résoudra probablement vos problèmes : https://github.com/LINCnil/pia/releases/tag/1.5.0

**Comment by ylachgar** [comment]
Bonjour @brunto 

Je n'ai implementé que la derrniere version (1.5.0) de PIA front & Back :)
Je pense réellement que la compilation prod a un problem de conf, j'aimerai vraiment votre support sur ce debugage :)

Merci d'avance.

**Comment by brunto** [comment]
Ok, your package.json doesn't have the good version number.
I propose you to follow this steps:

1. Verify the content of the file **src/environments/environment.prod.ts** : 

```
export const environment = {
  name: 'production',
  production: true,
  version: '1.5.0',
  rollbar_key: ''
};
```

2. Execute the commands below:

```
rm -rf node_modules
npm install -g @angular/cli
npm install
ng build -e prod
```

For the next version we could build the app with `ng build --prod  --build-optimizer --sourcemaps`

**Comment by ylachgar** [comment]
Thanks for your reply,

I don't have any src/environments/environment.prod.ts file, only a .example one so i did copy it and change de content as you advise, also running the below command with sudo.

everything work find until the build of prod env as you can see below : 

![image](https://user-images.githubusercontent.com/35890640/35984222-43a7eb52-0cf4-11e8-9f8c-084c0cd6d8c4.png)

**Comment by brunto** [comment]
This is error is because a file is missing.
Did you rename the file `environment.prod.ts.example` in `environment.prod.ts`?

**Comment by ylachgar** [comment]
Yes copied and renamed

**Comment by ylachgar** [comment]
Hi All,

I solved the issue with isolating prod environment and attribute another piaback which lead to fully funtionnal 1.5.0 version in front.

I will send to all the full installation runbook in Ubuntu in the next days, with screenshoots and explanation on ubuntu side :)

**Comment by jnthnkabongo** [comment]
Salut, la famille j'ai un projet Angular qui après construction me donne pas d'erreur mais dès que je déploie j'ai une page blanche que faire ??
