### ISSUE TITLE
problem with ng build

### ISSUE THREAD

**Issue by xyko0** [LINCnil/pia#490]
Hello,
I'm trying to install PIA on CentOS7 for our company. 
"pia-back" is OK and working. But I have an issue with "pia-front".
I'm not familiar with Angular CLI and when I'm executing : 
`# ng build --prod --build-optimizer --source-map`

I get this return : 
```
Your global Angular CLI version (9.1.9) is greater than your local
version (8.3.22). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
An unhandled exception occurred: Cannot find module '@angular/compiler'
Require stack:
- /home/admpia/pia/node_modules/@angular/compiler-cli/index.js
- /home/admpia/pia/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js
- /home/admpia/pia/node_modules/@ngtools/webpack/src/index.js
- /home/admpia/pia/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js
- /home/admpia/pia/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/index.js
- /home/admpia/pia/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /home/admpia/pia/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/admpia/pia/node_modules/@angular-devkit/architect/node/index.js
- /home/admpia/pia/node_modules/@angular/cli/models/architect-command.js
- /home/admpia/pia/node_modules/@angular/cli/commands/build-impl.js
- /home/admpia/pia/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/admpia/pia/node_modules/@angular-devkit/schematics/tools/index.js
- /home/admpia/pia/node_modules/@angular/cli/utilities/json-schema.js
- /home/admpia/pia/node_modules/@angular/cli/models/command-runner.js
- /home/admpia/pia/node_modules/@angular/cli/lib/cli/index.js
- /usr/lib/node_modules/@angular/cli/lib/init.js
- /usr/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/admpia/pia/node_modules/@angular/compiler-cli/index.js:21:22
    at /home/admpia/pia/node_modules/@angular/compiler-cli/index.js:3:17
    at Object.<anonymous> (/home/admpia/pia/node_modules/@angular/compiler-cli/index.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/admpia/pia/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:12:24)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/admpia/pia/node_modules/@ngtools/webpack/src/index.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
```

Could you help me make it work please ?
Thank you for the help.
Best regards
Baptiste

**Comment by xyko0** [comment]
I did a npm install @angular/compiler (hope it was a good move) and now I got this : 
`You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.`

**Comment by xyko0** [comment]
With some despair I did : 
```
npm install rxjs@^6.4.0
npm install angular2-csv
npm install tslib
```

And it started compilating, but I got this : 
```
chunk {0} runtime.a8ef3a8272419c2e2c66.js, runtime.a8ef3a8272419c2e2c66.js.map (runtime) 1.51 kB [entry] [rendered]
chunk {1} main.fb4cc3b472296d1b1ab4.js, main.fb4cc3b472296d1b1ab4.js.map (main) 4.01 MB [initial] [rendered]
chunk {2} polyfills.d5a940c41b45775777bf.js, polyfills.d5a940c41b45775777bf.js.map (polyfills) 43.1 kB [initial] [rendered]
chunk {3} polyfills-es5.4e354fb4e1b79cca892e.js, polyfills-es5.4e354fb4e1b79cca892e.js.map (polyfills-es5) 123 kB [initial] [rendered]
chunk {4} styles.2ed7de1ccd9f97c72227.css, styles.2ed7de1ccd9f97c72227.css.map (styles) 103 kB [initial] [rendered]
chunk {scripts} scripts.6ea8fafd940959689b8e.js, scripts.6ea8fafd940959689b8e.js.map (scripts) 521 kB [entry] [rendered]
Date: 2020-06-24T15:22:01.485Z - Hash: baeec083aa7c7fb57f2a - Time: 161226ms

WARNING in ./node_modules/@angular/compiler/src/util.js 10:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

ERROR in ./src/app/cards/card-item/card-item.component.ts
Module not found: Error: Can't resolve 'jszip' in '/home/admpia/pia/src/app/cards/card-item'
ERROR in ./src/app/cards/list-item/list-item.component.ts
Module not found: Error: Can't resolve 'jszip' in '/home/admpia/pia/src/app/cards/list-item'
ERROR in ./src/app/shared/export/export.component.ts
Module not found: Error: Can't resolve 'jszip' in '/home/admpia/pia/src/app/shared/export'
```

**Comment by xyko0** [comment]
`npm install jszip` fixed my problem !
App is working now and I can connect on it.
I hope I did it well and this can help people in the same situation.

Sorry for the spam.
Best regards.
Baptiste
